FROM eclipse-temurin:17-jdk-alpine
# DB
ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD

ENV DB_URL=$DB_URL
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD

# JWT
ARG JWT_SECRET_KEY
ARG JWT_EXPIRATION_ACCESS_TOKEN
ARG JWT_EXPIRATION_REFRESH_TOKEN

ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV JWT_EXPIRATION_ACCESS_TOKEN=$JWT_EXPIRATION_ACCESS_TOKEN
ENV JWT_EXPIRATION_REFRESH_TOKEN=$JWT_EXPIRATION_REFRESH_TOKEN

# LOG
ARG LOG_IP
ARG LOG_PORT
ARG LOG_LEVEL
ARG SHOW_SQL

ENV LOG_IP=$LOG_IP
ENV LOG_PORT=$LOG_PORT
ENV LOG_LEVEL=$LOG_LEVEL
ENV SHOW_SQL=$SHOW_SQL

# REDIS
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_USERNAME
ARG REDIS_PASSWORD

ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV REDIS_USERNAME=$REDIS_USERNAME
ENV REDIS_PASSWORD=$REDIS_PASSWORD

VOLUME /tmp
COPY target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
EXPOSE 9000
